name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg pkg-config xvfb libgl1-mesa-dev mesa-utils libgl1

    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.3.0

    - name: Configure poetry
      shell: bash
      run: python -m poetry config virtualenvs.in-project true

    - name: View poetry version
      run: poetry --version

    - name: Install dependencies
      run: |
        python -m poetry install

    - name: Test
      run: xvfb-run --auto-servernum poetry run pytest -v

  Build_and_Release:
    needs: Quality
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' && 
      !contains ( github.event.head_commit.message, 'chore(release)' )
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    outputs:
      released: ${{ steps.release-status.outputs.released }}

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.3.0

      - name: Check release status
        id: release-status
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install python-semantic-release
          if semantic-release --noop --strict version
          then
            echo "released=true" >> $GITHUB_OUTPUT
            echo "Releasing new version."
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "Skipping release steps."
          fi

      - if: steps.release-status.outputs.released == 'true'
        name: Release and Build
        id: github-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          git fetch --tags
          poetry build
          
          # Get the latest tag to upload release assets
          TAG=$(git describe --tags --abbrev=0)
          
          for file in ./dist/**
            do gh release upload "$TAG" $file
          done

      - if: steps.release-status.outputs.released == 'true'
        name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  Publish_PyPI:
    needs: Build_and_Release
    if: needs.Build_and_Release.outputs.released == 'true'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1